<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseSystemDrawing>true</UseSystemDrawing>
    <AssemblyName>HshDetectionEngin.Plate</AssemblyName>
    <RootNamespace>HshDetectionEngin.Plate</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\HshDetectionEngin.Abstractions\HshDetectionEngin.Abstractions.csproj" />
    <ProjectReference Include="..\HshDetectionEngin.Licensing\HshDetectionEngin.Licensing.csproj" />
    <PackageReference Include="Emgu.CV" Version="4.13.0.5924" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.29.0" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Models\plate_yolo.hshmodel" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="Models\plate_yolo_fallback.hshmodel" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="Models\ocr_crnn.hshmodel" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="Models\ocr_crnn.labels.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="Models\ocr_crnn.ocr.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="Models\ocr_cnn.hshmodel" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="Models\ocr_cnn.labels.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="Models\ocr_cnn.ocr.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="Models\chars_best_v26.hshmodel" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="Models\chars_best_v26_int8.hshmodel" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="Models\chars_best_v26.labels.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="Models\chars_best_v26.ocr.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="Models\chars_best_v26_int8.ocr.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
