import { Alert, Box, Checkbox, CircularProgress, Divider, FormControl, FormControlLabel, IconButton, InputLabel, MenuItem, Paper, Select, TextField, Tooltip, Typography } from '@mui/material';
import AddRoundedIcon from '@mui/icons-material/AddRounded';
import DeleteOutlineRoundedIcon from '@mui/icons-material/DeleteOutlineRounded';
import EditRoundedIcon from '@mui/icons-material/EditRounded';
import FormatListNumberedRoundedIcon from '@mui/icons-material/FormatListNumberedRounded';
import RefreshRoundedIcon from '@mui/icons-material/RefreshRounded';
import { AppDataGrid } from '../AppDataGrid';
import { AppGroupBox } from '../AppGroupBox';
import { CrudDialog } from '../CrudDialog';
import { WorkspaceToolbar } from '../WorkspaceToolbar';
import { ConfirmDialog } from '../ConfirmDialog';
import { MoneyTextField } from '../MoneyTextField';
import type { Language } from '../../i18n';
import { formatMoney } from '../../utils/formatters';
import { idOf, parkSpacesCount, parkingSpaceId, spaceSectionId, valueOf, type DefinitionKind, type DefinitionRow } from './definitionDomain';
import { useDefinitionCrud } from './useDefinitionCrud';

type Props = { kind: DefinitionKind; parkingId: number; language: Language; title: string; pageTitle: string; canEdit: boolean; canDelete: boolean };

export function DefinitionCrudView(props: Props) {
  const state = useDefinitionCrud(props);
  const { kind, language, title, copy } = state;
  const { pageTitle } = props;
  const fields = <Box className="parking-floor-form-fields form-section-column">
    <AppGroupBox title={title} className={`parking-floor-main-group${kind === 'member-kinds' ? ' membership-kind-group' : ''}`}>
      <TextField label={copy.title} value={state.form.Title} onChange={(event) => { state.setForm({ ...state.form, Title: event.target.value }); }} autoFocus required slotProps={{ htmlInput: { maxLength: 100 } }} error={Boolean(state.fieldErrors.Title)} helperText={state.fieldErrors.Title} />
      {kind === 'member-kinds' && <FormControl fullWidth error={Boolean(state.fieldErrors.MembershipType)}><InputLabel>{copy.membershipType}</InputLabel><Select inputProps={{ 'aria-label': copy.membershipType }} label={copy.membershipType} value={state.form.MembershipType} onChange={(event) => { const next = String(event.target.value); state.setForm({ ...state.form, MembershipType: next, MembershipCreditType: next === '0' ? '1' : state.form.MembershipCreditType }); }}>{copy.membershipValues.map((label, index) => <MenuItem key={label} value={index}>{label}</MenuItem>)}</Select>{state.fieldErrors.MembershipType && <Typography variant="caption" color="error">{state.fieldErrors.MembershipType}</Typography>}</FormControl>}
      {kind === 'floors' && <Box className="parking-floor-space-summary"><Typography variant="caption" color="text.secondary">{language === 'fa' ? `تعداد جای‌پارک: ${state.spaceRows.length} | فعال: ${state.spaceRows.filter((space) => space.IsActive).length}` : `Spaces: ${state.spaceRows.length} | Active: ${state.spaceRows.filter((space) => space.IsActive).length}`}</Typography></Box>}
      {kind === 'zones' && <><FormControl fullWidth required><InputLabel>{language === 'fa' ? 'طبقه' : 'Floor'}</InputLabel><Select label={language === 'fa' ? 'طبقه' : 'Floor'} value={String(state.zoneFloorId ?? '')} disabled={state.zoneFloorLocked} onChange={(event) => { state.setZoneFloorId(Number(event.target.value) || null); state.setSelectedZoneSpaceIds([]); }}>{state.floorRows.map((floor, index) => <MenuItem key={String(idOf(floor, index))} value={idOf(floor, index)}>{String(valueOf(floor, 'Title') ?? '—')}</MenuItem>)}</Select></FormControl><Box className="parking-zone-space-picker"><Typography variant="caption" color="text.secondary">{language === 'fa' ? `تعداد جای‌پارک‌های طبقه: ${state.zoneFloorSpaceCount} | قابل انتخاب: ${state.zoneSpaces.length} | تخصیص‌یافته به این زون: ${state.selectedZoneSpaceIds.length}` : `Floor spaces: ${state.zoneFloorSpaceCount} | Selectable: ${state.zoneSpaces.length} | Assigned to this zone: ${state.selectedZoneSpaceIds.length}`}</Typography>{!state.zoneFloorId ? <Typography variant="body2" color="text.secondary">{language === 'fa' ? 'ابتدا طبقه را انتخاب کنید.' : 'Select a floor first.'}</Typography> : state.zoneFloorSpacesLoading ? <Box className="inline-status-row"><CircularProgress size={16} /><Typography variant="body2" color="text.secondary">{language === 'fa' ? 'در حال دریافت جای‌پارک‌ها...' : 'Loading parking spaces...'}</Typography></Box> : state.zoneSpaces.length === 0 ? <Typography variant="body2" color="text.secondary">{language === 'fa' ? 'برای این طبقه جای‌پارکی ثبت نشده است.' : 'No parking spaces are registered on this floor.'}</Typography> : <AppDataGrid direction={language === 'fa' ? 'rtl' : 'ltr'} rows={state.zoneSpaces} rowKey={(space, index) => parkingSpaceId(space, index)} selectedKeys={state.selectedZoneSpaceIds} onSelectionChange={(keys) => state.setSelectedZoneSpaceIds(keys.map(Number))} columns={[{ key: 'Title', label: copy.title, render: (space) => String(valueOf(space, 'Title') ?? '—') }, { key: 'Kind', label: language === 'fa' ? 'نوع جای‌پارک' : 'Space type', render: (space) => String(valueOf(space, 'ParkingParkSpaceKindTitle') ?? valueOf(space, 'ParkingParkSpaceKind') ?? '—') }, { key: 'Section', label: language === 'fa' ? 'وضعیت تخصیص' : 'Assignment', render: (space) => spaceSectionId(space) > 0 ? (language === 'fa' ? 'تخصیص‌یافته به این زون' : 'Assigned to this zone') : (language === 'fa' ? 'آزاد' : 'Available') }]} />}</Box></>}
    </AppGroupBox>
    {kind === 'member-kinds' && <AppGroupBox title={language === 'fa' ? 'حق عضویت / اعتبار' : 'Membership fee / credit'} className="membership-credit-group membership-kind-group"><FormControl fullWidth error={Boolean(state.fieldErrors.MembershipCreditType)}><InputLabel>{copy.creditType}</InputLabel><Select inputProps={{ 'aria-label': copy.creditType }} label={copy.creditType} value={state.form.MembershipCreditType} disabled={Number(state.form.MembershipType) === 0} onChange={(event) => state.setForm({ ...state.form, MembershipCreditType: String(event.target.value) })}>{copy.creditValues.map((label, index) => <MenuItem key={label} value={index}>{label}</MenuItem>)}</Select>{state.fieldErrors.MembershipCreditType && <Typography variant="caption" color="error">{state.fieldErrors.MembershipCreditType}</Typography>}</FormControl><MoneyTextField label={copy.fee} value={state.form.MembershipFee} onValueChange={(value) => state.setForm({ ...state.form, MembershipFee: value })} error={Boolean(state.fieldErrors.MembershipFee)} helperText={state.fieldErrors.MembershipFee} /><TextField label={copy.duration} type="number" value={state.form.DurationDays} disabled={Number(state.form.MembershipCreditType) === 0} onChange={(event) => state.setForm({ ...state.form, DurationDays: event.target.value })} error={Boolean(state.fieldErrors.DurationDays)} helperText={state.fieldErrors.DurationDays ?? (Number(state.form.MembershipCreditType) === 0 ? (language === 'fa' ? 'برای اعتبار اعتباری نامحدود است.' : 'Unlimited for credit membership.') : undefined)} slotProps={{ htmlInput: { min: 0, step: 1 } }} /><TextField label={copy.refund} type="number" value={state.form.RefundDeadlineDayCount} onChange={(event) => state.setForm({ ...state.form, RefundDeadlineDayCount: event.target.value })} error={Boolean(state.fieldErrors.RefundDeadlineDayCount)} helperText={state.fieldErrors.RefundDeadlineDayCount} slotProps={{ htmlInput: { min: 0, step: 1 } }} /></AppGroupBox>}
    {kind === 'member-kinds' && <AppGroupBox title={copy.tariffs} className="membership-kind-group"><Typography variant="body2" color="text.secondary">{state.memberKindTariffs.length > 0 ? state.memberKindTariffs.map((tariff) => String(valueOf(tariff, 'Title'))).join('، ') : (language === 'fa' ? 'تعرفه‌ای متصل نشده است.' : 'No related tariff.')}</Typography></AppGroupBox>}
    {kind === 'floors' && <AppGroupBox title={language === 'fa' ? 'جای‌پارک‌های وابسته' : 'Parking spaces'} className="parking-floor-spaces-group"><WorkspaceToolbar ariaLabel={language === 'fa' ? 'ابزارهای جای‌پارک' : 'Parking space actions'}><Tooltip title={language === 'fa' ? 'جای‌پارک جدید' : 'New space'} arrow><IconButton size="small" color="primary" aria-label={language === 'fa' ? 'جای‌پارک جدید' : 'New space'} onClick={state.openCreateSpace}><AddRoundedIcon /></IconButton></Tooltip><Tooltip title={language === 'fa' ? 'ایجاد بازه‌ای جای‌پارک' : 'Generate a range'} arrow><IconButton size="small" aria-label={language === 'fa' ? 'ایجاد بازه‌ای جای‌پارک' : 'Generate a range'} onClick={state.openCreateSpaceRange}><FormatListNumberedRoundedIcon /></IconButton></Tooltip><Tooltip title={copy.edit} arrow><span><IconButton size="small" aria-label={copy.edit} onClick={state.openEditSpace} disabled={state.selectedSpaceIndexes.length !== 1}><EditRoundedIcon /></IconButton></span></Tooltip><Tooltip title={copy.remove} arrow><span><IconButton size="small" color="error" aria-label={copy.remove} onClick={state.removeSpace} disabled={state.selectedSpaceIndexes.length === 0}><DeleteOutlineRoundedIcon /></IconButton></span></Tooltip></WorkspaceToolbar>{state.spaceRows.length === 0 ? <Typography variant="body2" color="text.secondary">{language === 'fa' ? 'جای‌پارکی برای این طبقه ثبت نشده است.' : 'No parking spaces have been added.'}</Typography> : <AppDataGrid direction={language === 'fa' ? 'rtl' : 'ltr'} rows={state.spaceRows} rowKey={(_, index) => index} selectedKey={state.selectedSpaceIndex} selectedKeys={state.selectedSpaceIndexes} onSelectionChange={(keys) => { const indexes = keys.map(Number); state.setSelectedSpaceIndexes(indexes); state.setSelectedSpaceIndex(indexes.length === 1 ? indexes[0] : null); }} onRowClick={(_, index) => { state.setSelectedSpaceIndex(index); state.setSelectedSpaceIndexes([index]); }} columns={[{ key: 'Title', label: copy.title, render: (row) => row.Title || '—' }, { key: 'Kind', label: language === 'fa' ? 'نوع جای‌پارک' : 'Space type', render: (row) => String(valueOf(state.spaceKinds.find((kindRow) => Number(valueOf(kindRow, 'Id')) === row.ParkingParkSpaceKindId) ?? {}, 'Title') ?? '—') }, { key: 'IsActive', label: language === 'fa' ? 'وضعیت' : 'Status', trueLabel: language === 'fa' ? 'فعال' : 'Active', falseLabel: language === 'fa' ? 'غیرفعال' : 'Inactive' }]} />}</AppGroupBox>}
    {(kind === 'floors' || kind === 'zones') && <TextField label={copy.description} value={state.form.Description} onChange={(event) => state.setForm({ ...state.form, Description: event.target.value })} multiline minRows={2} slotProps={{ htmlInput: { maxLength: 2000 } }} />}
  </Box>;

  const columns = kind === 'member-kinds' ? [{ key: 'Title', label: copy.title, render: (row: DefinitionRow) => String(valueOf(row, 'Title') ?? '—') }, { key: 'MembershipFee', label: copy.fee, render: (row: DefinitionRow) => <span dir="ltr">{formatMoney(String(valueOf(row, 'MembershipFee') ?? '0'))}</span> }, { key: 'DurationDays', label: copy.duration, render: (row: DefinitionRow) => String(valueOf(row, 'DurationDays') ?? '0') }, { key: 'MembershipCreditType', label: copy.creditType, render: (row: DefinitionRow) => copy.creditValues[Number(valueOf(row, 'MembershipCreditType'))] ?? '—' }, { key: 'MembershipType', label: copy.membershipType, render: (row: DefinitionRow) => copy.membershipValues[Number(valueOf(row, 'MembershipType'))] ?? '—' }, { key: 'RefundDeadlineDayCount', label: copy.refund, render: (row: DefinitionRow) => String(valueOf(row, 'RefundDeadlineDayCount') ?? '0') }] : [{ key: 'Title', label: copy.title, render: (row: DefinitionRow) => String(valueOf(row, 'Title') ?? '—') }, ...(kind === 'floors' || kind === 'zones' ? [{ key: 'ParkSpaces', label: language === 'fa' ? 'جای‌پارک‌ها' : 'Parking spaces', render: (row: DefinitionRow) => String(parkSpacesCount(row)) }] : kind === 'space-types' ? [{ key: 'IsUsing', label: copy.using, trueLabel: language === 'fa' ? 'در حال استفاده' : 'In use', falseLabel: language === 'fa' ? 'بدون استفاده' : 'Not in use' }] : [{ key: 'Description', label: copy.description, render: (row: DefinitionRow) => String(valueOf(row, 'Description') ?? '—') }])];

  return <Paper className={`home-workspace parking-management-workspace parking-definition-crud-workspace parking-definition-${kind}`} elevation={0}><Box className="workspace-heading workspace-heading-unified"><Box className="workspace-page-context"><Typography component="h1" variant="h1">{pageTitle}</Typography><Typography component="span" className="workspace-heading-separator">-</Typography><Typography variant="h6">{title}</Typography><Typography variant="body2" color="text.secondary">{state.rows.length} {language === 'fa' ? 'رکورد' : 'records'}</Typography></Box><Tooltip title={copy.refresh} arrow><IconButton className="workspace-refresh-button" aria-label={copy.refresh} onClick={() => void state.load()} disabled={state.loading}><RefreshRoundedIcon /></IconButton></Tooltip></Box><WorkspaceToolbar ariaLabel={language === 'fa' ? 'ابزارهای صفحه' : 'Page actions'}><Tooltip title={copy.add} arrow><span><IconButton className="workspace-toolbar-icon-button" color="primary" aria-label={copy.add} onClick={state.openCreate} disabled={!state.canEdit}><AddRoundedIcon /></IconButton></span></Tooltip><Tooltip title={copy.edit} arrow><span><IconButton className="workspace-toolbar-icon-button" aria-label={copy.edit} onClick={() => void state.openEdit()} disabled={!state.canEdit || !state.selected || state.selectedIds.length !== 1}><EditRoundedIcon /></IconButton></span></Tooltip><Tooltip title={copy.remove} arrow><span><IconButton className="workspace-toolbar-icon-button" color="error" aria-label={copy.remove} onClick={() => state.setDeleteDialogOpen(true)} disabled={!state.canDelete || state.selectedIds.length === 0}><DeleteOutlineRoundedIcon /></IconButton></span></Tooltip></WorkspaceToolbar><Divider sx={{ my: 2 }} />{state.message && <Alert severity="success" sx={{ mb: 2 }}>{state.message}</Alert>}{state.error && <Alert severity="error" sx={{ mb: 2 }}>{state.error}</Alert>}{state.loading && <Box className="inline-status-row"><CircularProgress size={20} /><Typography variant="body2">{copy.loading}</Typography></Box>}{!state.loading && !state.error && state.rows.length === 0 && <Alert severity="info">{copy.empty}</Alert>}{!state.loading && !state.error && state.rows.length > 0 && <AppDataGrid direction={language === 'fa' ? 'rtl' : 'ltr'} rows={state.rows} rowKey={(row, index) => idOf(row, index)} selectedKey={state.selectedId} selectedKeys={state.selectedIds} onSelectionChange={(keys) => { const ids = keys.map(Number); state.setSelectedIds(ids); state.setSelectedId(ids.length === 1 ? ids[0] : null); }} onRowClick={(row, index) => { const id = idOf(row, index); state.setSelectedId(id); state.setSelectedIds([id]); }} columns={columns} />}
    <CrudDialog open={state.dialogOpen} title={state.form.Id ? copy.update : copy.create} onClose={() => state.setDialogOpen(false)} onConfirm={() => void state.save()} cancelLabel={copy.cancel} confirmLabel={copy.save} busy={state.saving} maxWidth={kind === 'zones' ? 'md' : 'sm'}>{fields}</CrudDialog>
    <CrudDialog open={state.spaceDialogOpen} title={state.spaceForm.Id ? (language === 'fa' ? 'ویرایش جای‌پارک' : 'Edit parking space') : (language === 'fa' ? 'افزودن جای‌پارک' : 'Add parking space')} onClose={() => state.setSpaceDialogOpen(false)} onConfirm={state.saveSpace} cancelLabel={copy.cancel} confirmLabel={copy.save} maxWidth="sm"><Box className="form-section-column"><AppGroupBox className="parking-space-editor-group" title={language === 'fa' ? 'مشخصات جای‌پارک' : 'Parking space information'}><TextField label={copy.title} value={state.spaceForm.Title} onChange={(event) => state.setSpaceForm({ ...state.spaceForm, Title: event.target.value })} autoFocus required /><FormControl fullWidth required><InputLabel>{language === 'fa' ? 'نوع جای‌پارک' : 'Space type'}</InputLabel><Select label={language === 'fa' ? 'نوع جای‌پارک' : 'Space type'} value={String(state.spaceForm.ParkingParkSpaceKindId || '')} onChange={(event) => state.setSpaceForm({ ...state.spaceForm, ParkingParkSpaceKindId: Number(event.target.value) })}>{state.spaceKinds.map((spaceKind) => <MenuItem key={String(valueOf(spaceKind, 'Id'))} value={Number(valueOf(spaceKind, 'Id'))}>{String(valueOf(spaceKind, 'Title') ?? '')}</MenuItem>)}</Select></FormControl><FormControlLabel control={<Checkbox checked={state.spaceForm.IsActive} onChange={(event) => state.setSpaceForm({ ...state.spaceForm, IsActive: event.target.checked })} />} label={language === 'fa' ? 'فعال' : 'Active'} /></AppGroupBox></Box></CrudDialog>
    <CrudDialog open={state.spaceRangeDialogOpen} title={language === 'fa' ? 'ایجاد بازه‌ای جای‌پارک' : 'Generate parking-space range'} onClose={() => state.setSpaceRangeDialogOpen(false)} onConfirm={state.saveSpaceRange} cancelLabel={copy.cancel} confirmLabel={copy.save} maxWidth="sm"><Box className="form-section-column"><AppGroupBox className="parking-space-editor-group" title={language === 'fa' ? 'الگوی نام‌گذاری' : 'Naming pattern'}><TextField label={language === 'fa' ? 'پیشوند' : 'Prefix'} value={state.spaceRangeForm.prefix} onChange={(event) => state.setSpaceRangeForm({ ...state.spaceRangeForm, prefix: event.target.value })} autoFocus required placeholder="A" /><Box className="parking-space-range-inputs"><TextField fullWidth label={language === 'fa' ? 'از' : 'From'} type="number" value={state.spaceRangeForm.from} onChange={(event) => state.setSpaceRangeForm({ ...state.spaceRangeForm, from: event.target.value })} required /><TextField fullWidth label={language === 'fa' ? 'تا' : 'To'} type="number" value={state.spaceRangeForm.to} onChange={(event) => state.setSpaceRangeForm({ ...state.spaceRangeForm, to: event.target.value })} required /></Box><FormControl fullWidth required><InputLabel>{language === 'fa' ? 'نوع جای‌پارک' : 'Space type'}</InputLabel><Select label={language === 'fa' ? 'نوع جای‌پارک' : 'Space type'} value={String(state.spaceRangeForm.ParkingParkSpaceKindId || '')} onChange={(event) => state.setSpaceRangeForm({ ...state.spaceRangeForm, ParkingParkSpaceKindId: Number(event.target.value) })}>{state.spaceKinds.map((spaceKind) => <MenuItem key={String(valueOf(spaceKind, 'Id'))} value={Number(valueOf(spaceKind, 'Id'))}>{String(valueOf(spaceKind, 'Title') ?? '')}</MenuItem>)}</Select></FormControl><FormControlLabel control={<Checkbox checked={state.spaceRangeForm.IsActive} onChange={(event) => state.setSpaceRangeForm({ ...state.spaceRangeForm, IsActive: event.target.checked })} />} label={language === 'fa' ? 'فعال' : 'Active'} /></AppGroupBox></Box></CrudDialog>
    <ConfirmDialog open={state.deleteDialogOpen} title={copy.remove} message={state.selectedIds.length > 1 ? (language === 'fa' ? `آیا از حذف ${state.selectedIds.length} رکورد انتخاب‌شده مطمئن هستید؟` : `Delete ${state.selectedIds.length} selected records?`) : `${copy.removeConfirm} ${state.selected ? `${copy.title}: ${String(valueOf(state.selected, 'Title') ?? idOf(state.selected))}` : ''}`} cancelLabel={copy.cancel} confirmLabel={copy.remove} onClose={() => state.setDeleteDialogOpen(false)} onConfirm={() => void state.remove()} busy={state.loading} />
  </Paper>;
}
